# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-08-15 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id_empleados', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empleado', models.CharField(max_length=150)),
                ('cedula_empleado', models.CharField(max_length=350)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleados',
            },
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id_permisos', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_desde', models.DateField(max_length=150)),
                ('fecha_hasta', models.DateField(max_length=150)),
                ('id_empleados', models.ForeignKey(db_column='id_empleados', on_delete=django.db.models.deletion.DO_NOTHING, to='appmacas.Empleados')),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'db_table': 'permisos',
            },
        ),
        migrations.CreateModel(
            name='TipoAusencias',
            fields=[
                ('id_tipoausencias', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Tipo Ausencia',
                'verbose_name_plural': 'Tipos de Ausencia',
                'db_table': 'tipoausencias',
            },
        ),
        migrations.AddField(
            model_name='permisos',
            name='id_tipoausencias',
            field=models.ForeignKey(db_column='id_tipoausencias', on_delete=django.db.models.deletion.DO_NOTHING, to='appmacas.TipoAusencias'),
        ),
        migrations.AddField(
            model_name='empleados',
            name='id_tipoausencias',
            field=models.ForeignKey(db_column='id_tipoausencia', on_delete=django.db.models.deletion.DO_NOTHING, to='appmacas.TipoAusencias'),
        ),
    ]
