# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-08-15 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmacas', '0002_auto_20190815_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisos',
            name='fecha_desde',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='permisos',
            name='fecha_hasta',
            field=models.DateField(),
        ),
    ]
